version: '3.7'

services:

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
