version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:3000"
    command: server.js

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"