version: '3.7'

services:

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    depends_on:
      - postgres
    command: sh wait_for.sh postgres:5432 -- sh -c "npx prisma db push"



